Repository wazo-platform/wazo-auth, pull requests merged in 2020-11, with the labels that each got.

#117 Pull request for WAZO-2083-remove-confd-call
  debian/control
  etc/wazo-auth/config.yml
  requirements.txt
  setup.py
  wazo_auth/__init__.py
  wazo_auth/config.py
  wazo_auth/interfaces.py
  wazo_auth/plugins/backends/ldap_user.py
  wazo_auth/plugins/backends/wazo_user.py
  wazo_auth/plugins/metadata/default_user.py
Labels: mergeit

#120 admin policy: add agent stats permission
  alembic/versions/24ffaae58c03_add_agent_stats_acl.py
Labels: mergeit

#123 groups: add searchable columns to openapi doc
  wazo_auth/plugins/http/groups/api.yml
Labels: auto-merge, mergeit

#121 close session on token expiration
  wazo_auth/token.py
Labels: mergeit

#118 Pull request for WAZO-2081-remove-acl-template-feature
  CHANGELOG.md
  alembic/versions/548fcce8aad9_remove_template_from_acl.py
  integration_tests/assets/etc/wazo-auth/conf.d/asset.base.yml
  integration_tests/suite/database/test_db_policy.py
  integration_tests/suite/database/test_db_tenant.py
  integration_tests/suite/helpers/base.py
  integration_tests/suite/helpers/fixtures/db.py
  integration_tests/suite/helpers/fixtures/http.py
  integration_tests/suite/test_acl.py
  integration_tests/suite/test_group_policy.py
  integration_tests/suite/test_http_interface.py
  integration_tests/suite/test_policies.py
  integration_tests/suite/test_tenants.py
  integration_tests/suite/test_user_group.py
  integration_tests/suite/test_users.py
  wazo_auth/__init__.py
  wazo_auth/database/queries/policy.py
  wazo_auth/helpers.py
  wazo_auth/interfaces.py
  wazo_auth/plugins/backends/ldap_user.py
  wazo_auth/plugins/backends/tests/test_ldap_user.py
  wazo_auth/plugins/backends/wazo_user.py
  wazo_auth/plugins/http/policies/api.yml
  wazo_auth/plugins/http/policies/http.py
  wazo_auth/plugins/http/policies/plugin.py
  wazo_auth/plugins/http/policies/schemas.py
  wazo_auth/plugins/metadata/default_external_api.py
  wazo_auth/plugins/metadata/default_internal.py
  wazo_auth/plugins/metadata/default_user.py
  wazo_auth/services/group.py
  wazo_auth/services/policy.py
  wazo_auth/services/token.py
  wazo_auth/services/user.py
  wazo_auth/tests/test_helpers.py
  wazo_auth/tests/test_services.py
Labels: mergeit

#119 Pull request for WAZO-2090-deprecate-token-acls-field
  CHANGELOG.md
  integration_tests/suite/database/test_db_token.py
  integration_tests/suite/helpers/base.py
  integration_tests/suite/helpers/fixtures/db.py
  integration_tests/suite/test_group_policy.py
  integration_tests/suite/test_http_interface.py
  integration_tests/suite/test_wazo_user_backend.py
  wazo_auth/database/models.py
  wazo_auth/database/queries/token.py
  wazo_auth/exceptions.py
  wazo_auth/flask_helpers.py
  wazo_auth/http.py
  wazo_auth/interfaces.py
  wazo_auth/plugins/backends/ldap_user.py
  wazo_auth/plugins/backends/tests/test_ldap_user.py
  wazo_auth/plugins/backends/wazo_user.py
  wazo_auth/plugins/http/password_reset/http.py
  wazo_auth/plugins/http/tokens/api.yml
  wazo_auth/plugins/http/tokens/http.py
  wazo_auth/services/email.py
  wazo_auth/services/token.py
  wazo_auth/tests/test_tokens.py
  wazo_auth/token.py
Labels: mergeit

#124 bus: use correct policy for publishing
  wazo_auth/bus.py
Labels: auto-merge

#122 Pull request for WAZO-2037-refactor-acl-db
  alembic/alembic_acl_template.py.mako
  alembic/versions/17ce2e46c43e_migrate_acl_tbl_to_token_column.py
  alembic/versions/40d8f37d7096_rename_acl_template_table_to_access.py
  integration_tests/suite/database/test_db_policy.py
  integration_tests/suite/database/test_db_tenant.py
  wazo_auth/database/models.py
  wazo_auth/database/queries/policy.py
  wazo_auth/database/queries/token.py
  wazo_auth/database/queries/user.py
  wazo_auth/exceptions.py
Labels: mergeit

#125 Pull request for WAZO-2092-remove-unused-metadata
  CHANGELOG.md
  integration_tests/suite/test_default_token_metadata.py
  integration_tests/suite/test_wazo_user_backend.py
  wazo_auth/interfaces.py
  wazo_auth/plugins/metadata/default_external_api.py
  wazo_auth/plugins/metadata/default_internal.py
  wazo_auth/plugins/metadata/default_user.py
Labels: mergeit

#126 fix corrupt acl
  alembic/versions/40d8f37d7096_rename_acl_template_table_to_access.py
  alembic/versions/d779d0640bd7_fix_corrupt_acl.py
Labels: mergeit

#127 fix_corrupt_acl: remove the index during the script
  alembic/versions/d779d0640bd7_fix_corrupt_acl.py
Labels: mergeit
