Repository wazo-platform/wazo-auth, pull requests merged in 2021-04, with the labels that each got.

#142 Pull request for WAZO-2297-policy-slug
  CHANGELOG.md
  alembic/versions/23a680f792f5_add_policy_slug.py
  integration_tests/suite/database/test_db_policy.py
  integration_tests/suite/helpers/base.py
  integration_tests/suite/helpers/constants.py
  integration_tests/suite/helpers/fixtures/db.py
  integration_tests/suite/helpers/fixtures/http.py
  integration_tests/suite/test_auth_microsoft.py
  integration_tests/suite/test_google.py
  integration_tests/suite/test_group_policy.py
  integration_tests/suite/test_policies.py
  integration_tests/suite/test_tenants.py
  wazo_auth/bootstrap.py
  wazo_auth/database/models.py
  wazo_auth/database/queries/filters.py
  wazo_auth/database/queries/policy.py
  wazo_auth/plugins/http/group_policy/http.py
  wazo_auth/plugins/http/policies/api.yml
  wazo_auth/plugins/http/policies/http.py
  wazo_auth/plugins/http/policies/schemas.py
  wazo_auth/schemas.py
  wazo_auth/services/all_users.py
  wazo_auth/services/policy.py
  wazo_auth/services/tenant.py
Labels: mergeit

#144 Pull request for small-refactor-improvement
  CHANGELOG.md
  integration_tests/Makefile
  integration_tests/suite/database/test_db_external_auth.py
  integration_tests/suite/database/test_db_group.py
  integration_tests/suite/database/test_db_policy.py
  integration_tests/suite/database/test_db_refresh_token.py
  integration_tests/suite/database/test_db_session.py
  integration_tests/suite/database/test_db_tenant.py
  integration_tests/suite/database/test_db_token.py
  integration_tests/suite/database/test_db_user.py
  integration_tests/suite/helpers/fixtures/db.py
  integration_tests/suite/helpers/fixtures/http.py
  integration_tests/suite/test_default_token_metadata.py
  integration_tests/suite/test_emails.py
  integration_tests/suite/test_group_policy.py
  integration_tests/suite/test_groups.py
  integration_tests/suite/test_http_interface.py
  integration_tests/suite/test_mobile.py
  integration_tests/suite/test_password_reset.py
  integration_tests/suite/test_policies.py
  integration_tests/suite/test_sessions.py
  integration_tests/suite/test_tenants.py
  integration_tests/suite/test_token.py
  integration_tests/suite/test_user_group.py
  integration_tests/suite/test_user_session.py
  integration_tests/suite/test_users.py
  integration_tests/suite/test_wazo_user_backend.py
  wazo_auth/database/models.py
  wazo_auth/interfaces.py
  wazo_auth/plugins/http/policies/api.yml
  wazo_auth/plugins/http/policies/plugin.py
  wazo_auth/plugins/http/policies/schemas.py
  wazo_auth/plugins/http/tokens/api.yml
  wazo_auth/plugins/http/tokens/schemas.py
  wazo_auth/schemas.py
  wazo_auth/services/token.py
  wazo_auth/tests/test_services.py
  wazo_auth/token.py
Labels: mergeit

#145 Pull request for WAZO-2312-default-policies-config-file
  README.md
  alembic/alembic_acl_template.py.mako
  alembic/script.py.mako
  alembic/versions/caede349e1ab_set_default_policy_managed.py
  alembic_revision.sh
  wazo_auth/config.py
  wazo_auth/controller.py
  wazo_auth/services/__init__.py
  wazo_auth/services/all_users.py
  wazo_auth/services/default_policy.py
Labels: mergeit

#146 Pull request for WAZO-2312-default-policies-config-file-2
  alembic/versions/12a91e0863f5_create_the_default_user_policy.py
  alembic/versions/191d15471531_add_call_log_user_created_event_acl_to_.py
  alembic/versions/192f49b6ec34_add_webhookd_acl_to_users.py
  alembic/versions/1b1a4931ea84_add_agent_acl.py
  alembic/versions/1c19f4acd0bd_add_user_cdr_acl.py
  alembic/versions/1e5140290977_add_plugin_event_acl_to_the_admin_.py
  alembic/versions/2c1a43889d04_create_the_wazo_default_admin_policy.py
  alembic/versions/35bcf76df780_add_acl_for_new_chat_message__events.py
  alembic/versions/50de5600b678_add_websocket_and_events_access_to_root_.py
  alembic/versions/52a21739a22a_add_call_logs_read_to_root.py
  alembic/versions/582f09b464de_add_webhookd_acl_to_root.py
  alembic/versions/9e376c1e7473_add_wazo_user_acl_to_root.py
  alembic/versions/ffe8284b62d9_add_plugind_access_to_root_user.py
  etc/wazo-auth/config.yml
  integration_tests/assets/etc/wazo-auth/conf.d/50-default.yml
  integration_tests/suite/database/test_db_policy.py
  integration_tests/suite/test_policies.py
  integration_tests/suite/test_wazo_user_backend.py
  wazo_auth/config.py
Labels: auto-merge

#147 migrate same slug/name on different tenant
  alembic/versions/23a680f792f5_add_policy_slug.py
Labels: mergeit

#148 Pull request for avoid-delete-automatic-policy
  integration_tests/suite/database/test_db_policy.py
  integration_tests/suite/test_group_policy.py
  wazo_auth/database/queries/policy.py
  wazo_auth/services/all_users.py
  wazo_auth/services/default_policy.py
  wazo_auth/services/policy.py
Labels: mergeit

#149 Pull request for WAZO-2317-shared-default-policies
  integration_tests/assets/etc/wazo-auth/conf.d/asset.base.yml
  integration_tests/suite/helpers/constants.py
  integration_tests/suite/test_group_policy.py
  integration_tests/suite/test_policies.py
  integration_tests/suite/test_tenants.py
  wazo_auth/controller.py
  wazo_auth/database/queries/filters.py
  wazo_auth/database/queries/policy.py
  wazo_auth/database/queries/tenant.py
  wazo_auth/plugins/http/group_policy/http.py
  wazo_auth/schemas.py
  wazo_auth/services/all_users.py
  wazo_auth/services/default_policy.py
  wazo_auth/services/group.py
  wazo_auth/services/tenant.py
Labels: mergeit

#151 remove duplicate config-managed policies
  alembic/versions/56cea38f6815_remove_config_managed_policies_from_.py
Labels: mergeit

#150 Pull request for WAZO-2315-factorize-access-check
  wazo_auth/tests/test_tokens.py
  wazo_auth/token.py
Labels: mergeit

#152 test: use explicit ipv4 addr to connect docker
  integration_tests/suite/helpers/base.py
  integration_tests/suite/helpers/constants.py
  integration_tests/suite/test_auth_microsoft.py
  integration_tests/suite/test_documentation.py
  integration_tests/suite/test_external_auth.py
  integration_tests/suite/test_google.py
  integration_tests/suite/test_ldap_backend.py
  integration_tests/suite/test_policies.py
Labels: auto-merge, mergeit
